<Project>
    
    <PropertyGroup>
        <Version>1.28.4-preview1</Version>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFrameworks>netframework472;net8.0</TargetFrameworks>
        <Deterministic>true</Deterministic>
        <Nullable>disable</Nullable>
        <LangVersion>12</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
        <RepositoryUrl>https://github.com/masa-iwm/GstSharpBundle</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>
</Project>